export const data = [
  {
    id: "1",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    id: "2",
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    id: "3",
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "4",
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "5",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    id: "6",
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    id: "7",
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "8",
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "9",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    id: "10",
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    id: "11",
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "12",
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "13",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    id: "14",
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    id: "15",
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "16",
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "21",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    id: "22",
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    id: "23",
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "24",
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "25",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    id: "26",
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    id: "27",
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "31",
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "32",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    id: "33",
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    id: "34",
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "35",
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "36",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    id: "37",
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    id: "38",
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "41",
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "42",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
  {
    id: "43",
    firstName: "Babaa",
    lastName: "heyyoyoy",
    age: 51,
    visits: 12,
    progress: 0.42,
    status: "124123123",
  },
  {
    id: "44",
    firstName: "right on bruh",
    lastName: "pants my man",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "45",
    firstName: "War everywere",
    lastName: "Penny",
    age: 555,
    visits: 51,
    progress: 2.3,
    status: "123",
  },
  {
    id: "46",
    firstName: "Enrico",
    lastName: "Valbuena",
    age: 14,
    visits: 5,
    progress: 0.3,
    status: "Complicated",
  },
]
